### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by ollibolli** [qfox/pym#3]
The package.json point to index.js that is missing and make it impossible to require. (using prowserify)

**Comment by zxqfox** [comment]
Going to fix this

**Comment by qfox** [comment]
I've added missing file, should be fine now.

```
$ npm publish
+ pym@0.1.1
```

Please check this with v0.1.1. Ty!

**Comment by ollibolli** [comment]
Great 
Thanks a lot.

Olle Svensson

Telefon: 070 162 24 44
Epost: olle.svensson@schibsted.se
